# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-02 18:23:08
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Standard"
description: "Runs standard build and test steps"

inputs:
  operating_system:
    required: true
    type: string

  python_version:
    required: true
    type: string

  script_prefix:
    required: true
    type: string

  script_extension:
    required: true
    type: string

  shell_name:
    required: true
    type: string

  source_command:
    required: true
    type: string

  sudo_command:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Placeholder
      shell: ${{ inputs.shell_name }}
      run: |
        echo "Placeholder"
